import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const [image, setImage] = useState(null);

  useEffect(() => {
    fetch('/api/getproduct')
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        const blob = new Blob([new Uint8Array(data.image.data)], { type: 'image/jpeg' })
        const imageUrl = URL.createObjectURL(blob);
        // URL.revokeObjectURL(imageUrl);
        setImage(imageUrl);
        console.log(imageUrl);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          image &&
          <div style={{ background: "red", "padding": "24px" }}>
            <img src={image} alt="" />
            <img src={image} alt="" />
            <img src={image} alt="" />
            <img src={image} alt="" />
            <img src={image} alt="" />
          </div>
        }

      </main>
    </>
  )
}
